name: Critical Issue Created
on:
  issues:
    types: [opened, reopened]
  workflow_dispatch:
jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: 'U04KL38250R'
          payload: |
            {
              "unfurl_links": false,
              "unfurl_media": false,
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "A new issue has been created!"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Issue:*\n<${{ github.event.issue.html_url }}|${{ github.event.issue.title }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Opened By:*\n<${{ github.event.issue.user.html_url }}|${{ github.event.issue.user.login }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n<${{ github.event.repository.html_url }}|${{ github.event.repository.full_name }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Labels:*\n${{ join(github.event.issue.labels.*.name, ', ') }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Assignees:*\n${{ join(github.event.issue.assignees.*.login, ', ') }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "```${{ github.event.issue.body }}```"
                  }
                }
              ]
            }