name: Pull Request Merged
on:
  pull_request:
    types: [closed]
jobs:
  close-issue:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get linked issues of a PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_ID: ${{ github.event.pull_request.node_id }}
        run: |
          linked_issue_id="$( gh api graphql -f query='
          query ($id: ID!) {
            node(id: $id) {
              ... on PullRequest {
                timelineItems(first: 100, itemTypes: [CONNECTED_EVENT]) {
                  nodes {
                    ... on ConnectedEvent {
                      subject {
                         ... on Issue { number }
                      }
                    }
                  }
                }
              }
            }
          }' -f id=$PR_ID --jq '.data.node.timelineItems.nodes[].subject.number')"
          echo "Linked issue id: $linked_issue_id"
          echo "PR id: $PR_ID"
