name: Pull Request Merged
on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      pr_id:
        description: "Pull Request ID"
        required: true
jobs:
  move-issue-card:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Gather Cards
        id: gather-cards
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_ID: ${{ github.event.pull_request.node_id }}
          INPUT_PR_ID: ${{ github.event.inputs.pr_id }}
        run: |
          # if INPUT_PR_ID is set, use that instead of PR_ID
          if [ -n "$INPUT_PR_ID" ]; then
            PR_ID=$INPUT_PR_ID
          fi

          issues="$( gh api graphql -f query='
          query {
            node (id: $PR_ID) {
              ... on PullRequest {
                closingIssuesReferences(first: 10) {
                  edges {
                    node {
                      ... on Issue {
                        projectCards(first: 100) {
                          nodes {
                            ... on ProjectCard {
                              project {
                                id
                                name
                                columns (first: 100) {
                                  nodes {
                                    id
                                    databaseId
                                    name
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }' -f id=$PR_ID --jq '.data.node.closingIssuesReferences.edges[]')"
          echo "Issues: $issues"

